## Theme Documentation: https://learn.netlify.com/en/

baseURL = "https://akhoury6.github.io/rbcli/"
languageCode = "en-us"
title = "RBCli Documentation"
theme = "hugo-theme-learn"

[params]
# Can be "red", "blue", or "green", or comment out for purple
themeVariant = "blue"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "github"
url = "https://github.com/akhoury6/rbcli"
weight = 10

#[[menu.shortcuts]]
#name = "<i class='fas fa-camera'></i> Showcases"
#url = "/showcase"
#weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-gem'></i> Rubygems"
identifier = "rubygems"
url = "https://rubygems.org/gems/rbcli"
weight = 20

#[[menu.shortcuts]]
#name = "<i class='fas fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
