# https://www.mkdocs.org/user-guide/configuration

site_name: RBCli Documentation
site_description: Description
site_author: Andrew Khoury
copyright: Copyright © 2018 Andrew Khoury

pages:
  - Home: index.md
  - Tutorial:
    - Getting Started: tutorial/10-getting_started.md
    - The Project Layout: tutorial/20-project_layout.md
    - Your First Command: tutorial/30-your_first_command.md
    - Options, Parameters, and Arguments: tutorial/40-options_parameters_and_arguments.md
    - Publishing and Distribution: tutorial/50-publishing.md
  - Advanced Features:
    - User Config Files: advanced/user_config_files.md
    - Hooks: advanced/hooks.md
    - Automatic Updates: advanced/automatic_updates.md
    - State Storage: advanced/state_storage.md
    - Distributed State Locking: advanced/distributed_state_locking.md
    - Script Wrapping: advanced/script_wrapping.md
  - Development:
    - Contribution Guide: development/contributing.md
    - License Info: development/license.md
    - Code of Conduct: development/code_of_conduct.md

# The repo link on the top-right of the page
#repo_name: GitHub
repo_url: https://github.com/akhoury6/rbcli/
edit_uri: ''

# For use with mkdocs build
#docs_dir: ./docs-src/docs/
site_dir: ../docs/

# For use with gh-deploy
#remote_branch: master
#remote_name: origin

#theme: windmill

#theme:
#  name: material
#  logo:
#     icon: devices    # from https://material.io/tools/icons/?style=baseline
#  feature:
#    tabs: true
#  logo: 'images/logo.svg'
#   palette:
#     primary: 'indigo'
#     accent: 'indigo'
#   language: 'en'
#   direction: 'ltr'
#   favicon: 'assets/images/favicon.ico'


#theme: readthedocs
#theme:
#  name: mkdocs
#  custom_dir: my_theme_customizations/
#  static_templates:
#   - sitemap.html
#  include_sidebar: false
#extra_css:
#    - css/extra.css
#    - css/second_extra.css
#extra_javascript:
#extra_templates:
#extra:
#  rbcli_version: 0.1.0

# For formatting options see https://www.mkdocs.org/user-guide/configuration/#formatting-options