#!/usr/bin/env ruby

#########################################################
### <%= @vars[:cmdname] %>
#######
## This is the main executable for <%= @vars[:cmdname] %>.
## It's job is to load and execute the application.
##
## You should not need to edit this file.
#########################################################

require_relative '../lib/<%= @vars[:cmdname] %>'

#########################
## Configuration Block ##
#########################
# This block is where rbcli is configured.
# Any options marked as Optional can be commented out.
# Options marked as Multiple can be declared multiple times.
#########################

Rbcli::Configurate.me do
	####
	# GENERAL
	###
	# These parameters are for genreal information about your application.
	###

	## Script Name -- (Required) -- This line identifies the tool's executable on the command line.
	# To change it, rename this file to the command you want and this will pick up that name automatically.
	# You can change it manually if needed, but this should work for most cases.
	scriptname File.basename(__FILE__)

	## Version Number -- (Required)
	# Here we reference the same constant that we set for our Gem. If not using Rubygems you can change this to
	# a version in the standard 'major.minor.patch' format (i.e.: 1.4.0)
	version Project::VERSION
end

##################
## Load Project ##
##################
# Here we load the project into Rbcli
##################
Rbcli.load_project

#####################
## Parse Statement ##
#####################
# When this statement is called, the CLI will be
# parsed and code executed.
#####################
Rbcli.parse
